### ISSUE TITLE
06-mitsuzen-hdi-10-left-arm - Suggested optimization.

### ISSUE THREAD

**Issue by darvell** [t04glovern/awesome-exapunks#1]
Howdy, I know you're just using this as a text reference for your playthrough but thought I'd suggest an alternative solution for puzzle 6.

Using XA to do one part of the clamp and XB to do the other reduces your cycles to 184. You might be able to reduce the size some more if you really want to get in to it but I'm at a loss.

XA:

```
LINK 800
MARK READ
COPY #NERV X
TEST X > 50
TJMP CLAMPOVER
COPY X M
JUMP READ

MARK CLAMPOVER
COPY 50 M
JUMP READ
```

XB:

```
LINK 800
@REP 4
LINK 1
@END
MARK LOOP
COPY M X
TEST X < -120
TJMP CLAMPUNDER
COPY X #NERV
JUMP LOOP

MARK CLAMPUNDER
COPY -120 #NERV
JUMP LOOP
```

**Comment by t04glovern** [comment]
Awesome find, that's far better. If its okay with you, I'll add it as an alternate optimisation to the README for that specific challenge. 

Last thing I want to do is to publish all the best of the best optimisations moving forward; since it would make the leaderboard redundant in game. I like your solution though as it uses the @REP and @END commands and might be helpful for people learning.
